services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command : bash -c 'cd app && yarn dev'
    volumes:
      - ./app:/app
      - modules:/app/node_modules
    ports:
      - "3000"
volumes:
  modules:
    driver: local